version: 0.2

phases:
  build:
    commands:
      - echo "Running the batch script..."
      - chmod +x script.sh
      - chmod +x script.bat
      - ./script.sh
      - ./script.bat

artifacts:
  files:
    - '**/*'
